---
- hosts: all
  vars_files:
    - defaults/main.yml
  pre_tasks:
    - name: Install python build deps
      become: true
      command: yum-builddep python -y
    - name: install deps
      become: true
      yum:
        name={{"{{"}} item {{"}}"}}
        state=latest
      with_items:
        - vim
        - wget
        - policycoreutils-python
        - git
  roles:
   - { role: samsixtyone.epel, become: true }
   - { role: FrogyYen.centos7-nginx, become: true }
   - { role: geerlingguy.redis, become: true }
   - { role: olibob.nodejs, become: true }
   - { role: ice9js.mongodb, become: true }
   - { role: jffz.netdata, become: true }
  tasks:
    - name: install the latest version of JQ
      become: true
      yum: name=jq state=latest
    - name: py35 | Check that py35 is still not installed
      become: true
      stat: path="{{"{{"}} py35_bin {{"}}"}}"
      register: py35_already_installed
      ignore_errors: True
    - name: py35 | Download
      get_url:
        url="{{"{{"}} py35_url {{"}}"}}"
        dest="{{"{{"}} py35_tar_file {{"}}"}}"
        checksum="md5:{{"{{"}} py35_md5 {{"}}"}}"
      when: py35_already_installed.stat.exists == false
    - name: py35 | Uncompress
      unarchive:
        src={{"{{"}} py35_tar_file {{"}}"}}
        dest=/tmp
        copy=no
        creates="{{"{{"}} py35_sources {{"}}"}}"
      when: py35_already_installed.stat.exists == false
    - name: py35 | Compile and install
      become: true
      command: "{{"{{"}} item {{"}}"}}"
      args:
        chdir: "{{"{{"}} py35_sources {{"}}"}}"
      with_items:
        - "./configure --prefix {{"{{"}} py35_install {{"}}"}}"
        - make
        - make install
      when: py35_already_installed.stat.exists == false
    - name: py35 | Create python_major_version symlink
      become: true
      file:
        src={{"{{"}} py35_bin {{"}}"}}
        dest='/bin/python3.5'
        state=link
      when: py35_already_installed.stat.exists == false
    - name: py35 | Create python_major_version symlink
      become: true
      file:
        src={{"{{"}} py35_bin {{"}}"}}
        dest='/usr/local/bin/python'
        state=link
      when: py35_already_installed.stat.exists == false
    - name: pip35 | Create pip symlink
      become: true
      file:
        src={{"{{"}} pip35_bin {{"}}"}}
        dest='/bin/pip3.5'
        state=link
      when: py35_already_installed.stat.exists == false
    - name: pip35 | Create pip symlink
      become: true
      file:
        src={{"{{"}} py35_bin {{"}}"}}
        dest='/usr/local/bin/pip'
        state=link
      when: py35_already_installed.stat.exists == false
    - name: Mongo service
      become: true
      service: state=started name=mongod
    - name: Redis service
      become: true
      service: state=started name=redis
    - name: install the yarn's repo
      become: true
      shell: wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo
    - name: install the latest version of yarn
      become: true
      yum: name=yarn state=latest
    - name: install cookiecutter
      become: true
      pip: executable="pip3.5" name=cookiecutter
    # PROJECT SPECIFIC
    - name: Project config
      template: src=templates/project.yml.j2 dest=/home/vagrant/project.yml
    - name: Configure project
      shell: python /srv/python3.5.1/lib/python3.5/site-packages/cookiecutter/cli.py https://github.com/jf-parent/webbase --config-file /home/vagrant/project.yml --no-input
      ignore_errors: True
    - name: pip deps-dev
      pip: executable="pip3.5" requirements=/home/vagrant/{{cookiecutter.project_name}}/requirements-dev.txt
      become: true
    - name: Server config
      template: src=templates/server.json.j2 dest=/home/vagrant/{{cookiecutter.project_name}}/configs/server.json
    - name: nginx conf
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
      become: true
    - name: Social config
      template: src=templates/social_media.json.j2 dest=/home/vagrant/{{cookiecutter.project_name}}/configs/social_media.json
    - shell: yarn install
      args:
        chdir: /home/vagrant/{{cookiecutter.project_name}}
    - shell: npm run build:prod
      args:
        chdir: /home/vagrant/{{cookiecutter.project_name}}
      when: env == 'production'
    - shell: npm run build:dev
      args:
        chdir: /home/vagrant/{{cookiecutter.project_name}}
      when: env == 'development'
    - name: disable selinux
      selinux: state=disabled
      become: true
      when: env == 'development'
    - name: set httpd_can_network_connect selinux
      seboolean: name=httpd_can_network_connect state=yes persistent=yes
      become: true
      when: env == 'production'
    - shell: make server-dev
      args:
        chdir: /home/vagrant/{{cookiecutter.project_name}}
    - name: Nginx service
      become: true
      service: state=started name=nginx
